<style>
    nav ul {
        display: flex;
        list-style-type: none;
        padding: 0;
    }

    nav ul li {
        margin-right: 20px;
    }
</style>
<head>
    <title>내 웹사이트</title>
</head>
<header>
    <h1>내 웹사이트</h1>
    <nav>
        <%--ul 태그 가로로--%>
        <ul>
            <li><a href="/">홈</a></li>
            <li><a href="/about">소개</a></li>
            <li><a href="/contact">연락</a></li>
        </ul>
    </nav>
</header>
