gg:
  jte:
    developmentMode: true
    templateSuffix: .jte
    usePrecompiledTemplates: off

spring:
  application:
    name:
      vue-spring-location-postGis

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

  config:
    import: optional:file:jte-spring-geo-location-postgis-test-project-sub/secret-key.env[.properties]

kakao:
  map:
    api:
      key: ${KAKAO_MAP_API_KEY}
